### ISSUE TITLE
关于对抗训练。你是在feature向量，也就是bert最后一层的output上 进行的扰动？

### ISSUE THREAD

**Issue by waywaywayw** [xwen99/DuReader-Robust-With-Paddlehub#2]
不是应该在embedding上做扰动吗。你这样做受限于paddlehub的限制取不出来embedding层吗，还是说效果其实差不多

**Comment by xwen99** [comment]
复现了FGM，是在embedding上加的扰动，方法是梯度上升

**Comment by waywaywayw** [comment]
一般的类bert模型结构是这样吧：token ->token_embed ->transformer -> sequence_output 。然后拿 sequence_output 做下游任务。
你的self.feature 是 outputs["sequence_output"] 取出来的。所以是对 sequence_output 做的扰动。
原始论文 应该是对 token_embed 做扰动吧

**Comment by xwen99** [comment]
感谢指正，这里确实是我实现时的疏忽；实际使用上在 feature space 加扰动确实可以让结果对同一问题的不同变种明显更加鲁棒（但点数提升不明显），有空可以做个 embedding 扰动的对比实验

**Comment by waywaywayw** [comment]
找了挺多文档都没看到如何取出paddlehub的token_embed层。。这块你有什么想法吗

**Comment by xwen99** [comment]
我最开始是因为懒才用的paddlehub。。。后来魔改的时候就遇到很多坑，我感觉用paddlehub要改比较底层的东西还是比较难的。。不如试试huggingface。。。

**Comment by waywaywayw** [comment]
哈哈哈，我也是参加百度的比赛没办法。从你这学习了很多啦
关于 梯度计算还想请教一个小问题：
grad.stop_gradient = True 
你有把这句注释掉，这个是有什么问题吗？
我看tf源码也是有类似对应的语句的 
grad = tf.stop_gradient(grad)

**Comment by xwen99** [comment]
这里我其实就是照着tf原作实现写的。。但是paddle里加上这句后会难以收敛，所以注释掉了。。我对paddle的api不是很熟悉，所以可能这里实现是有些问题的

**Comment by waywaywayw** [comment]
了解了，我也是发现加上这句会出问题，embed层的参数不更新了。。
谢谢你的解答，周末愉快~
