### ISSUE TITLE
DuReader Dev Dataset

### ISSUE THREAD

**Issue by MrKolen** [xwen99/DuReader-Robust-With-Paddlehub#3]
您好，想问下DuReader_robust的验证集的答案位置标签是不是都是“-1”，你训练模型的时候是怎么利用的这部分数据？谢谢～

**Comment by xwen99** [comment]
你好，验证集中给出了答案串，可通过子串匹配获得答案位置标签。

**Comment by MrKolen** [comment]
> 你好，验证集中给出了答案串，可通过子串匹配获得答案位置标签。

感谢提示，有个问题，如下例子：
```
Question："爬行垫什么材质的好",
Context: "爬行垫根据中间材料的不同可以分为:XPE爬行垫、EPE爬行垫、EVA爬行垫、PVC爬行垫;其中XPE爬行垫、EPE爬行垫都属于PE材料加保鲜膜复合而成,都是无异味的环保材料,但是XPE爬行垫是品质较好的爬行垫"
Answer: "XPE"
```
考虑语义语境的话，正确答案应该是最后位置出现的“XPE”字符串，但是写规则匹配的话，一般会定位到开头位置的“XPE爬行垫”。
我的问题是，碰到类似句子中有重复出现的答案词的情况，你是怎么处理的？谢谢～

**Comment by xwen99** [comment]
> > 你好，验证集中给出了答案串，可通过子串匹配获得答案位置标签。
> 
> 感谢提示，有个问题，如下例子：
> 
> ```
> Question："爬行垫什么材质的好",
> Context: "爬行垫根据中间材料的不同可以分为:XPE爬行垫、EPE爬行垫、EVA爬行垫、PVC爬行垫;其中XPE爬行垫、EPE爬行垫都属于PE材料加保鲜膜复合而成,都是无异味的环保材料,但是XPE爬行垫是品质较好的爬行垫"
> Answer: "XPE"
> ```
> 
> 考虑语义语境的话，正确答案应该是最后位置出现的“XPE”字符串，但是写规则匹配的话，一般会定位到开头位置的“XPE爬行垫”。
> 我的问题是，碰到类似句子中有重复出现的答案词的情况，你是怎么处理的？谢谢～

你好，我没有对这种情况进行统计，但应当不会出现太多次，所以我没有做特殊处理；如果要求严格的话，可能要将这部分数据筛掉，或者手工标注。
